version: 2
jobs:
  build_docs:
    docker:
      - image: circleci/python:3.7-stretch
    steps:
      - checkout

      - run:
          name: Install oauthenticator
          command: |
            sudo pip install .

      - run:
          name: Install docs dependencies
          command: |
            sudo pip install -r docs/requirements.txt

      # Build the docs
      - run:
          name: Build docs to store
          command: |
            cd docs
            make html

      - store_artifacts:
          path: docs/build/html/
          destination: html

workflows:
  version: 2
  default:
    jobs:
      - build_docs
